// const String baseUrl = 'https://abiola.conceptrecall.com';
const String baseUrl = 'http://127.0.0.1:8000';
const String registerUrl = '$baseUrl/api/register';
const String loginUrl = '$baseUrl/api/login';
const String editProfileUrl = '$baseUrl/api/edit_profile';
const String PaypalUrl = '$baseUrl/api/process-transaction';
const String PaymentSettings = '$baseUrl/api/influencer_payment';
const String CategorySettings = '$baseUrl/api/influencer_category';
const String Paymentadd = '$baseUrl/api/payment_details';